# Generated by Django 4.0.6 on 2022-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('todo', 'Потрібно виконати'), ('in_progress', 'В процесі'), ('blocked', 'Заблоковано'), ('finished', 'Виконано')], default='todo', max_length=17),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'Низький'), ('medium', 'Середній'), ('low', 'Високий')], default='medium', max_length=8),
        ),
    ]
