# Generated by Django 4.0.6 on 2022-08-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_priority_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='status',
        ),
        migrations.AddField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Потрібно виконати'), ('in_progress', 'В процесі'), ('blocked', 'Заблоковано'), ('finished', 'Виконано')], default='todo', max_length=16),
        ),
    ]
